exp_name: ${model.name}_${model.dataset_type}
run_name: ${model.dataset_name}_${phase}
home_dir: /home/usrs/gzr1997
experiment:
  gpus:
    - 0
    - 1
    - 2
  accumulate_grad_batches: 1

log:
  log_dir: ${home_dir}/RESULTS/${exp_name}/${run_name}
  tb_save_dir: ${log.log_dir}/tb
  net_save_dir: ${log.log_dir}/net
  img_save_dir: ${log.log_dir}/img