# @package _group_
name: RwDCNMixedUp
ckpt: /home/usrs/gzr1997/RESULTS/RwDCNMixedUp_Ref10/None_train/net/epoch=12-val_ssim=0.8184.ckpt
#ckpt: /home/usrs/gzr1997/RESULTS/RwDCNMixedUp_Ref10/None_train/net/epoch=40-val_ssim=0.8185.ckpt
#ckpt: ~
dataset_type: Ref10
dataset_name: ~
lr_size:
  - 176
  - 320
batch_size: 4